version: "3.8"

services:
  remote1:
    build:
      context: ./micro-frontend-demo/remote1
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    networks:
      - microfrontend
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5174"]
      interval: 30s
      timeout: 10s
      retries: 3

  remote2:
    build:
      context: ./micro-frontend-demo/remote2
      dockerfile: Dockerfile
    ports:
      - "5175:5175"
    networks:
      - microfrontend
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5175"]
      interval: 30s
      timeout: 10s
      retries: 3

  host:
    build:
      context: ./micro-frontend-demo/host
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./micro-frontend-demo/host:/app
      - /app/node_modules
    networks:
      - microfrontend
    environment:
      - NODE_ENV=development
    depends_on:
      - remote1
      - remote2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  microfrontend:
    driver: bridge
